# Generated by Django 4.0.4 on 2022-05-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
