# Generated by Django 4.0.4 on 2022-05-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_alter_news_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
